/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--ey-page)',
        surface: 'var(--ey-card)',
        'surface-dim': 'var(--ey-page)',
        'surface-bright': 'var(--ey-card-raised)',
        'surface-variant': 'var(--ey-card-raised)',
        'surface-container': 'var(--ey-card)',
        'surface-container-low': 'var(--ey-page)',
        'surface-container-lowest': 'var(--ey-page)',
        'surface-container-high': 'var(--ey-card-raised)',
        'surface-container-highest': 'var(--ey-card-raised)',
        'surface-tint': 'var(--ey-accent)',
        'on-surface': 'var(--ey-ink)',
        'on-surface-variant': 'var(--ey-muted)',
        'on-background': 'var(--ey-ink)',
        outline: '#14213d',
        'outline-variant': 'var(--ey-line)',
        primary: 'var(--ey-ink)',
        'on-primary': 'var(--ey-page)',
        'primary-container': 'var(--ey-accent)',
        'on-primary-container': 'var(--ey-on-accent)',
        'primary-fixed': 'var(--ey-accent)',
        'primary-fixed-dim': 'var(--ey-accent)',
        'on-primary-fixed': 'var(--ey-on-accent)',
        'on-primary-fixed-variant': 'var(--ey-navy)',
        secondary: 'var(--ey-muted)',
        'on-secondary': 'var(--ey-ink)',
        'secondary-container': 'var(--ey-card-raised)',
        'on-secondary-container': 'var(--ey-ink)',
        tertiary: 'var(--ey-accent)',
        'on-tertiary': 'var(--ey-on-accent)',
        'tertiary-container': 'var(--ey-accent)',
        'on-tertiary-container': 'var(--ey-navy)',
        'tertiary-fixed': 'var(--ey-accent)',
        'tertiary-fixed-dim': 'var(--ey-accent)',
        error: '#93000a',
        'on-error': '#FFFFFF',
        'error-container': '#ffdad6',
        'on-error-container': '#690005',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '1.25rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
      },
      fontFamily: {
        sans: ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'headline-sm': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'display-lg': ['Geist', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'mono-label': ['Geist', 'monospace'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '500' }],
        'mono-label': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
