/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#060e20',
        surface: '#0b1325',
        'surface-dim': '#0b1325',
        'surface-bright': '#31394d',
        'surface-variant': '#2d3448',
        'surface-container': '#171f32',
        'surface-container-low': '#131b2e',
        'surface-container-lowest': '#060e20',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3448',
        'surface-tint': '#e9c400',
        'on-surface': '#dae2fc',
        'on-surface-variant': '#d0c6ab',
        'on-background': '#dae2fc',
        outline: '#999077',
        'outline-variant': '#4d4732',
        primary: '#fff6df',
        'on-primary': '#3a3000',
        'primary-container': '#ffd700',
        'on-primary-container': '#705e00',
        'primary-fixed': '#ffe16d',
        'primary-fixed-dim': '#e9c400',
        'on-primary-fixed': '#221b00',
        'on-primary-fixed-variant': '#544600',
        secondary: '#bfc6e0',
        'on-secondary': '#283044',
        'secondary-container': '#3f465c',
        'on-secondary-container': '#adb4ce',
        tertiary: '#defcff',
        'on-tertiary': '#00363a',
        'tertiary-container': '#00f1ff',
        'on-tertiary-container': '#006a70',
        'tertiary-fixed': '#79f5ff',
        'tertiary-fixed-dim': '#00dbe8',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
      },
      fontFamily: {
        sans: ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'headline-sm': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'display-lg': ['Geist', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'mono-label': ['Geist', 'monospace'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '500' }],
        'mono-label': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
